---
title: "Safegraph"
author: "Max O'Krepki"
date: "January 13, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(rjson)
```

```{r}
# Change this to take in a df instead
helper_function <- function(df){
  place <- df[[1]]
  cbgs  <- df[[2]]
  temp_vec <- unlist(fromJSON(json_str = cbgs))
  # All it's doing is repping the place as many times as there are home cbgs.
  return(data.frame("place" = rep(place, length(temp_vec)), "home_cbg" = names(temp_vec), "visitor_counts" = temp_vec))
}

# View(helper_function(test[1,]))
```

```{r}
# Import the dataset
test <- read_csv("test.csv")
# Filter out the rows with no cbgs
test <- test %>% filter(visitor_home_cbgs != "{}")

# Select only the needed columns
test <- test %>% select(c(location_name, visitor_home_cbgs))

cleaned_data <- do.call("rbind", apply(test, 1, helper_function))
```


```{r}
time <- proc.time()

# Import the dataset
m_1 <- read_csv("S:/Restricted Data Library/Safegraph/y=2018/m=1/part-00000-tid-6426590199993539346-61efb93e-41b7-44bf-80a7-c549c703927e-3038.c000.csv")
# Filter out the rows with no cbgs
m_1 <- m_1 %>% filter(visitor_home_cbgs != "{}")

# Select only the needed columns
m_1 <- m_1 %>% select(c(safegraph_place_id, visitor_home_cbgs))

cleaned_data_m_1 <- do.call("rbind", apply(m_1, 1, helper_function))

proc.time() - time
```

m = 1 took:
   user  system elapsed 
2046.06  135.06 2182.74

~36 minutes for ~122,000 rows. 
